os:
  - linux
  - osx

language:
  - cpp

addons:
  apt:
    packages:
      - libsndfile1-dev
      - libpulse-dev
      - libasound2-dev
      - cmake
      - nodejs

before_script:
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar xzf emsdk-portable.tar.gz
  - cd emsdk_portable && ./emsdk update
  - sed 's/clang-tag-%tag%-64bit/clang-tag-e%tag%-64bit/' -i emsdk_manifest.json
  - ./emsdk install latest && ./emsdk activate latest && cd ..

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./gradlew install -P audioArchitecture=pulse -i; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./gradlew install -i; fi
  - cd emsdk_portable && source ./emsdk_env.sh && cd ..
  - ./gradlew -i emscripten
  - sudo mv ./build/binaries/chuckExecutable/chuck /usr/local/bin/
  - cd src/test && python test.py

after_success:
  - echo "Success!"

after_failure:
  - echo "Something went wrong..."
