os:
  - linux
  - osx

language:
  - cpp

addons:
  apt:
    packages:
      - libsndfile1-dev
      - libpulse-dev
      - libasound2-dev

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./gradlew install -P audioArchitecture=pulse -i; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./gradlew install -i; fi
  - sudo mv ./build/install/chuckExecutable/chuck /usr/local/bin/
  - cd src/test && python test.py

after_success:
  - echo "Success!"

after_failure:
  - echo "Something went wrong..."
