sudo: false
language:
  - cpp
compiler:
  - clang
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - clang
      - libsndfile1-dev
      - libpulse-dev
      - libasound2-dev
      - nodejs
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.0-rc3-Linux-x86_64.tar.gz
  - tar xzf cmake-3.5.0-rc3-Linux-x86_64.tar.gz
  - export PATH=`pwd`/cmake-3.5.0-rc3-Linux-x86_64/bin:$PATH
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar xzf emsdk-portable.tar.gz
  - cd emsdk_portable && ./emsdk update
  - sed 's/clang-tag-%tag%-64bit/clang-tag-e%tag%-64bit/' -i emsdk_manifest.json
  - ./emsdk install -j1 latest && ./emsdk activate latest && cd ..

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./gradlew install -P audioArchitecture=pulse -i; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./gradlew install -i; fi
  - cd emsdk_portable && source ./emsdk_env.sh && cd ..
  - ./gradlew -i emscripten
  - export PATH=build/binaries/chuckExecutable/chuck:$PATH
  - cd src/test && python test.py

after_success:
  - echo "Success!"

after_failure:
  - echo "Something went wrong..."
